### PR TITLE
add compass turtle & update automata core

### PR DESCRIPTION
**Pull request by zyxkad**

### CODE REVIEW

**Comment by zyxkad** [comment]
@SirEndii However, there is no compass turtle's png image

**Comment by SirEndii** [comment]
@zyxkad 
Was your fork up to date?
There is a lot of stuff I changed

For example, your [pyproject.toml](https://github.com/zyxkad/Advanced-Peripherals-Documentation/blob/dev2/pyproject.toml) and mine

There is no lightgallery anymore and the last commit a year old (of pyproject.toml)
That's why the build fails

**Comment by zyxkad** [comment]
> @zyxkad Was your fork up to date? There is a lot of stuff I changed
> 
> For example, your [pyproject.toml](https://github.com/zyxkad/Advanced-Peripherals-Documentation/blob/dev2/pyproject.toml) and mine
> 
> There is no lightgallery anymore and the last commit a year old (of pyproject.toml) That's why the build fails

Ahh good point, I didn't notice that, rebased :)

**Comment by zyxkad** [comment]
@SirEndii Still needs the compass turtle's picture

**Pull request merged**
